apiVersion: apps/v1
kind: Deployment
metadata:
  name: YOUR-PROJECT-NAME        # CHANGE: all lowercase e.g. shoppingcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: YOUR-PROJECT-NAME     # CHANGE: all lowercase e.g. shoppingcart
  template:
    metadata:
      labels:
        app: YOUR-PROJECT-NAME   # CHANGE: all lowercase e.g. shoppingcart
    spec:
      containers:
      - name: YOUR-PROJECT-NAME  # CHANGE: all lowercase e.g. shoppingcart
        image: sabarishselva23/YOUR-PROJECT-NAME:latest  # CHANGE: all lowercase e.g. sabarishselva23/shoppingcart:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: YOUR-PROJECT-NAME-service  # CHANGE: all lowercase e.g. shoppingcart-service
spec:
  type: NodePort
  selector:
    app: YOUR-PROJECT-NAME         # CHANGE: all lowercase e.g. shoppingcart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # ⚠️ IMPORTANT: Change nodePort for EVERY new project to avoid conflict!
      # 1st project (interest-calculator) → 30008
      # 2nd project (shoppingcart)        → 30009
      # 3rd project                       → 30010
      # 4th project                       → 30011
      nodePort: 30008
